### ISSUE TITLE
URL bug while Crawling

### ISSUE THREAD

**Issue by RahulGala** [hardikvasa/webb#2]
Solve the URL bug: if 'www' is not passed in url then it does not start crawling

**Comment by hardikvasa** [comment]
Yes, will be working on it shortly! Thanks.

**Comment by dileepsankhla** [comment]
Even the link without http/https is not working. It says, "page not found"

**Comment by dileepsankhla** [comment]
And why use use urllib2 in download_page function when you are importing urllib?

**Comment by hardikvasa** [comment]
Issue resolved
